### ISSUE TITLE
Add Github Action CI for Maven Tests

### ISSUE THREAD

**Issue by vinamra28** [vinamra28/JHipster-Demo#2]

**Comment by geenva** [comment]
Can I do this? If yes, please assign me to this issue.

**Comment by vinamra28** [comment]
@flarely I'll have assigned one issue to you for npm tests. Probably I'll keep this for others

**Comment by twobiers** [comment]
Resolved in: https://github.com/vinamra28/JHipster-Demo/pull/4

Let me know if you're missing something.

**Comment by vinamra28** [comment]
closed in #4
